title: "Open-Source Portal Berlin"
defaults:
  -
    scope:
      path: "guides"
    values:
      layout: "projects-and-documents"
      type : "document"
  -
    scope:
      path: "projects"
    values:
      layout: "projects-and-documents"
      type: "project"
include: [README.md,CONTRIBUTING.md]
permalink: pretty

url: bnjmnsbl.github.io
# baseurl: /berlin-open-source-portal
